[package]
name = "arena-shared"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true, features = ["std", "bevy_log", "bevy_state", "serialize"] }
lightyear = { workspace = true, features = [
  "std",
  "replication",
  "prediction",
  "interpolation",
  "input_native",
  "netcode",
  "webtransport",
] }
ron = "0.12.2"
serde.workspace = true
